module.exports = {
  action: require('cli-mid-action'),
  boot: require('cli-mid-boot'),
  color: require('cli-mid-color'),
  command: require('cli-mid-command'),
  convert: require('cli-mid-convert'),
  debug: require('cli-mid-debug'),
  defaults: require('cli-mid-defaults'),
  ecommand: require('cli-mid-ecommand'),
  empty: require('cli-mid-empty'),

  emultiple: require('cli-mid-emultiple'),
  env: require('cli-mid-env'),
  erequired: require('./erequired'),
  error: require('./error'),
  eunknown: require('./eunknown'),
  events: require('./events'),
  exec: require('./exec'),
  help: require('cli-mid-help'),
  load: require('./load'),
  logger: require('./logger'),
  manual: require('./manual'),
  merge: require('./merge'),
  multiple: require('./multiple'),
  notify: require('./notify'),
  parser: require('./parser'),
  rc: require('./rc'),
  ready: require('./ready'),
  run: require('./run'),
  stdin: require('./stdin'),
  substitute: require('./substitute'),
  unparsed: require('./unparsed'),
  variables: require('./variables'),
  verbose: require('./verbose'),

  version: require('cli-mid-version')
}
